ERROR | 04/24/2023 09:02:34 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 4 | Hello
ERROR | 04/24/2023 09:02:34 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:02:34 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
ERROR | 04/24/2023 09:02:34 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:02:34 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
ERROR | 04/24/2023 09:02:34 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:02:34 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
DEBUG | 04/24/2023 09:02:34 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test
ERROR | 04/24/2023 09:02:34 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:02:34 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
ERROR | 04/24/2023 09:02:34 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:02:34 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
ERROR | 04/24/2023 09:02:34 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:02:34 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
DEBUG | 04/24/2023 09:02:34 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test
ERROR | 04/24/2023 09:02:34 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:02:34 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
ERROR | 04/24/2023 09:02:34 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:02:34 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
ERROR | 04/24/2023 09:02:34 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:02:34 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
DEBUG | 04/24/2023 09:02:34 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test
DEBUG | 04/24/2023 09:02:34 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test1
DEBUG | 04/24/2023 09:02:34 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test2
ERROR | 04/24/2023 09:02:34 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:02:34 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
DEBUG | 04/24/2023 09:02:34 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test1
ERROR | 04/24/2023 09:02:34 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:02:34 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
DEBUG | 04/24/2023 09:02:34 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test2
ERROR | 04/24/2023 09:02:34 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:02:34 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
DEBUG | 04/24/2023 09:02:34 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test1
DEBUG | 04/24/2023 09:02:34 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test2
DEBUG | 04/24/2023 09:02:34 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test1
DEBUG | 04/24/2023 09:02:34 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test2
DEBUG | 04/24/2023 09:02:34 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test3
ERROR | 04/24/2023 09:02:57 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 4 | Hello
ERROR | 04/24/2023 09:02:57 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:02:57 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
ERROR | 04/24/2023 09:02:57 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:02:57 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
ERROR | 04/24/2023 09:02:57 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:02:57 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
DEBUG | 04/24/2023 09:02:57 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test
ERROR | 04/24/2023 09:02:57 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:02:57 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
ERROR | 04/24/2023 09:02:57 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:02:57 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
ERROR | 04/24/2023 09:02:57 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:02:57 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
DEBUG | 04/24/2023 09:02:57 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test
ERROR | 04/24/2023 09:02:57 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:02:57 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
ERROR | 04/24/2023 09:02:57 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:02:57 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
ERROR | 04/24/2023 09:02:57 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:02:57 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
DEBUG | 04/24/2023 09:02:57 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test
DEBUG | 04/24/2023 09:02:57 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test1
DEBUG | 04/24/2023 09:02:57 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test2
ERROR | 04/24/2023 09:02:57 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:02:57 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
DEBUG | 04/24/2023 09:02:57 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test1
ERROR | 04/24/2023 09:02:57 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:02:57 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
DEBUG | 04/24/2023 09:02:57 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test2
ERROR | 04/24/2023 09:02:57 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:02:57 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
DEBUG | 04/24/2023 09:02:57 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test1
DEBUG | 04/24/2023 09:02:57 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test2
DEBUG | 04/24/2023 09:02:57 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test1
DEBUG | 04/24/2023 09:02:57 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test2
DEBUG | 04/24/2023 09:02:57 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test3
ERROR | 04/24/2023 09:19:29 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 4 | Hello
ERROR | 04/24/2023 09:19:29 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:19:29 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
ERROR | 04/24/2023 09:19:29 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:19:29 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
ERROR | 04/24/2023 09:19:29 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:19:29 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
DEBUG | 04/24/2023 09:19:29 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test
ERROR | 04/24/2023 09:19:29 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:19:29 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
ERROR | 04/24/2023 09:19:29 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:19:29 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
ERROR | 04/24/2023 09:19:29 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:19:29 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
DEBUG | 04/24/2023 09:19:29 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test
ERROR | 04/24/2023 09:19:29 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:19:29 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
ERROR | 04/24/2023 09:19:29 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:19:29 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
ERROR | 04/24/2023 09:19:29 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:19:29 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
DEBUG | 04/24/2023 09:19:29 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test
DEBUG | 04/24/2023 09:19:29 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test1
DEBUG | 04/24/2023 09:19:29 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test2
ERROR | 04/24/2023 09:19:29 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:19:29 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
DEBUG | 04/24/2023 09:19:29 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test1
ERROR | 04/24/2023 09:19:29 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:19:29 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
DEBUG | 04/24/2023 09:19:29 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test2
ERROR | 04/24/2023 09:19:29 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:19:29 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
DEBUG | 04/24/2023 09:19:29 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test1
DEBUG | 04/24/2023 09:19:29 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test2
DEBUG | 04/24/2023 09:19:29 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test1
DEBUG | 04/24/2023 09:19:29 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test2
DEBUG | 04/24/2023 09:19:29 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test3
ERROR | 04/24/2023 09:19:29 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 19 | a config field_name must be of type string.  Instead, a <class 'type'> was passed.
details - field_name: <class 'str'> | typ: <class 'str'> | default: default
ERROR | 04/24/2023 09:19:29 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 24 | a config field_name must not be empty.
details - field_name:  | typ: <class 'str'> | default: default
ERROR | 04/24/2023 09:20:12 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 4 | Hello
ERROR | 04/24/2023 09:20:12 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:20:12 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
ERROR | 04/24/2023 09:20:12 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:20:12 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
ERROR | 04/24/2023 09:20:12 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:20:12 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
DEBUG | 04/24/2023 09:20:12 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test
ERROR | 04/24/2023 09:20:12 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:20:12 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
ERROR | 04/24/2023 09:20:12 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:20:12 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
ERROR | 04/24/2023 09:20:12 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:20:12 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
DEBUG | 04/24/2023 09:20:12 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test
ERROR | 04/24/2023 09:20:12 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:20:12 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
ERROR | 04/24/2023 09:20:12 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:20:12 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
ERROR | 04/24/2023 09:20:12 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:20:12 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
DEBUG | 04/24/2023 09:20:12 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test
DEBUG | 04/24/2023 09:20:12 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test1
DEBUG | 04/24/2023 09:20:12 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test2
ERROR | 04/24/2023 09:20:12 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:20:12 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
DEBUG | 04/24/2023 09:20:12 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test1
ERROR | 04/24/2023 09:20:12 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:20:12 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
DEBUG | 04/24/2023 09:20:12 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test2
ERROR | 04/24/2023 09:20:12 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:20:12 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
DEBUG | 04/24/2023 09:20:12 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test1
DEBUG | 04/24/2023 09:20:12 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test2
DEBUG | 04/24/2023 09:20:12 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test1
DEBUG | 04/24/2023 09:20:12 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test2
DEBUG | 04/24/2023 09:20:12 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test3
ERROR | 04/24/2023 09:20:12 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 19 | a config field_name must be of type string.  Instead, a <class 'type'> was passed.
details - field_name: <class 'str'> | typ: <class 'str'> | default: default
ERROR | 04/24/2023 09:20:12 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 24 | a config field_name must not be empty.
details - field_name:  | typ: <class 'str'> | default: default
ERROR | 04/24/2023 09:20:21 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 4 | Hello
ERROR | 04/24/2023 09:20:21 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:20:21 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
ERROR | 04/24/2023 09:20:21 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:20:21 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
ERROR | 04/24/2023 09:20:21 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:20:21 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
DEBUG | 04/24/2023 09:20:21 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test
ERROR | 04/24/2023 09:20:21 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:20:21 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
ERROR | 04/24/2023 09:20:21 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:20:21 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
ERROR | 04/24/2023 09:20:21 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:20:21 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
DEBUG | 04/24/2023 09:20:21 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test
ERROR | 04/24/2023 09:20:21 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:20:21 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
ERROR | 04/24/2023 09:20:21 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:20:21 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
ERROR | 04/24/2023 09:20:21 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:20:21 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
DEBUG | 04/24/2023 09:20:21 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test
DEBUG | 04/24/2023 09:20:21 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test1
DEBUG | 04/24/2023 09:20:21 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test2
ERROR | 04/24/2023 09:20:21 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:20:21 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
DEBUG | 04/24/2023 09:20:21 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test1
ERROR | 04/24/2023 09:20:21 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:20:21 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
DEBUG | 04/24/2023 09:20:21 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test2
ERROR | 04/24/2023 09:20:21 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:20:21 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
DEBUG | 04/24/2023 09:20:21 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test1
DEBUG | 04/24/2023 09:20:21 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test2
DEBUG | 04/24/2023 09:20:21 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test1
DEBUG | 04/24/2023 09:20:21 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test2
DEBUG | 04/24/2023 09:20:21 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test3
ERROR | 04/24/2023 09:20:21 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 19 | a config field_name must be of type string.  Instead, a <class 'type'> was passed.
details - field_name: <class 'str'> | typ: <class 'str'> | default: default
ERROR | 04/24/2023 09:20:21 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 24 | a config field_name must not be empty.
details - field_name:  | typ: <class 'str'> | default: default
ERROR | 04/24/2023 09:22:41 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 4 | Hello
ERROR | 04/24/2023 09:22:41 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:22:41 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
ERROR | 04/24/2023 09:22:41 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:22:41 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
ERROR | 04/24/2023 09:22:41 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:22:41 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
DEBUG | 04/24/2023 09:22:41 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test
ERROR | 04/24/2023 09:22:41 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:22:41 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
ERROR | 04/24/2023 09:22:41 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:22:41 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
ERROR | 04/24/2023 09:22:41 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:22:41 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
DEBUG | 04/24/2023 09:22:41 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test
ERROR | 04/24/2023 09:22:41 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:22:41 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
ERROR | 04/24/2023 09:22:41 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:22:41 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
ERROR | 04/24/2023 09:22:41 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:22:41 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
DEBUG | 04/24/2023 09:22:41 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test
DEBUG | 04/24/2023 09:22:41 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test1
DEBUG | 04/24/2023 09:22:41 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test2
ERROR | 04/24/2023 09:22:41 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:22:41 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
DEBUG | 04/24/2023 09:22:41 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test1
ERROR | 04/24/2023 09:22:41 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:22:41 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
DEBUG | 04/24/2023 09:22:41 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test2
ERROR | 04/24/2023 09:22:41 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:22:41 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
DEBUG | 04/24/2023 09:22:41 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test1
DEBUG | 04/24/2023 09:22:41 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test2
DEBUG | 04/24/2023 09:22:41 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test1
DEBUG | 04/24/2023 09:22:41 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test2
DEBUG | 04/24/2023 09:22:41 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test3
ERROR | 04/24/2023 09:22:41 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 19 | a config field_name must be of type string.  Instead, a <class 'type'> was passed.
details - field_name: <class 'str'> | typ: <class 'str'> | default: default
ERROR | 04/24/2023 09:22:41 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 24 | a config field_name must not be empty.
details - field_name:  | typ: <class 'str'> | default: default
ERROR | 04/24/2023 09:23:01 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 4 | Hello
ERROR | 04/24/2023 09:23:01 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:23:01 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
ERROR | 04/24/2023 09:23:01 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:23:01 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
ERROR | 04/24/2023 09:23:01 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:23:01 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
DEBUG | 04/24/2023 09:23:01 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test
ERROR | 04/24/2023 09:23:01 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:23:01 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
ERROR | 04/24/2023 09:23:01 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:23:01 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
ERROR | 04/24/2023 09:23:01 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:23:01 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
DEBUG | 04/24/2023 09:23:01 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test
ERROR | 04/24/2023 09:23:01 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:23:01 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
ERROR | 04/24/2023 09:23:01 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:23:01 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
ERROR | 04/24/2023 09:23:01 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:23:01 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
DEBUG | 04/24/2023 09:23:01 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test
DEBUG | 04/24/2023 09:23:01 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test1
DEBUG | 04/24/2023 09:23:01 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test2
ERROR | 04/24/2023 09:23:01 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:23:01 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
DEBUG | 04/24/2023 09:23:01 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test1
ERROR | 04/24/2023 09:23:01 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:23:01 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
DEBUG | 04/24/2023 09:23:01 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test2
ERROR | 04/24/2023 09:23:01 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:23:01 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
DEBUG | 04/24/2023 09:23:01 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test1
DEBUG | 04/24/2023 09:23:01 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test2
DEBUG | 04/24/2023 09:23:01 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test1
DEBUG | 04/24/2023 09:23:01 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test2
DEBUG | 04/24/2023 09:23:01 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test3
ERROR | 04/24/2023 09:23:01 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 19 | a config field_name must be of type string.  Instead, a <class 'type'> was passed.
details - field_name: <class 'str'> | typ: <class 'str'> | default: default
ERROR | 04/24/2023 09:23:01 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 24 | a config field_name must not be empty.
details - field_name:  | typ: <class 'str'> | default: default
ERROR | 04/24/2023 09:24:11 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 4 | Hello
ERROR | 04/24/2023 09:24:11 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:24:11 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
ERROR | 04/24/2023 09:24:11 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:24:11 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
ERROR | 04/24/2023 09:24:11 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:24:11 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
DEBUG | 04/24/2023 09:24:11 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test
ERROR | 04/24/2023 09:24:11 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:24:11 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
ERROR | 04/24/2023 09:24:11 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:24:11 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
ERROR | 04/24/2023 09:24:11 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:24:11 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
DEBUG | 04/24/2023 09:24:11 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test
ERROR | 04/24/2023 09:24:11 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:24:11 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
ERROR | 04/24/2023 09:24:11 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:24:11 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
ERROR | 04/24/2023 09:24:11 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:24:11 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
DEBUG | 04/24/2023 09:24:11 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test
DEBUG | 04/24/2023 09:24:11 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test1
DEBUG | 04/24/2023 09:24:11 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test2
ERROR | 04/24/2023 09:24:11 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:24:11 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
DEBUG | 04/24/2023 09:24:11 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test1
ERROR | 04/24/2023 09:24:11 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:24:11 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
DEBUG | 04/24/2023 09:24:11 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test2
ERROR | 04/24/2023 09:24:11 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:24:11 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
DEBUG | 04/24/2023 09:24:11 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test1
DEBUG | 04/24/2023 09:24:11 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test2
DEBUG | 04/24/2023 09:24:11 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test1
DEBUG | 04/24/2023 09:24:11 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test2
DEBUG | 04/24/2023 09:24:11 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test3
ERROR | 04/24/2023 09:24:11 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 19 | a config field_name must be of type string.  Instead, a <class 'type'> was passed.
details - field_name: <class 'str'> | typ: <class 'str'> | default: default
ERROR | 04/24/2023 09:24:11 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 24 | a config field_name must not be empty.
details - field_name:  | typ: <class 'str'> | default: default
ERROR | 04/24/2023 09:24:11 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 29 | typ should be a type, specifying the type of object that the config field represents.  Instead, a <class 'str'> was passed.
details - field_name: name | typ: fail | default: default
ERROR | 04/24/2023 09:24:30 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 4 | Hello
ERROR | 04/24/2023 09:24:30 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:24:30 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
ERROR | 04/24/2023 09:24:30 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:24:30 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
ERROR | 04/24/2023 09:24:30 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:24:30 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
DEBUG | 04/24/2023 09:24:30 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test
ERROR | 04/24/2023 09:24:30 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:24:30 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
ERROR | 04/24/2023 09:24:30 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:24:30 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
ERROR | 04/24/2023 09:24:30 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:24:30 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
DEBUG | 04/24/2023 09:24:30 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test
ERROR | 04/24/2023 09:24:30 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:24:30 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
ERROR | 04/24/2023 09:24:30 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:24:30 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
ERROR | 04/24/2023 09:24:30 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:24:30 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
DEBUG | 04/24/2023 09:24:30 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test
DEBUG | 04/24/2023 09:24:30 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test1
DEBUG | 04/24/2023 09:24:30 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test2
ERROR | 04/24/2023 09:24:30 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:24:30 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
DEBUG | 04/24/2023 09:24:30 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test1
ERROR | 04/24/2023 09:24:30 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:24:30 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
DEBUG | 04/24/2023 09:24:30 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test2
ERROR | 04/24/2023 09:24:30 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:24:30 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
DEBUG | 04/24/2023 09:24:30 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test1
DEBUG | 04/24/2023 09:24:30 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test2
DEBUG | 04/24/2023 09:24:30 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test1
DEBUG | 04/24/2023 09:24:30 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test2
DEBUG | 04/24/2023 09:24:30 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test3
ERROR | 04/24/2023 09:24:30 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 19 | a config field_name must be of type string.  Instead, a <class 'type'> was passed.
details - field_name: <class 'str'> | typ: <class 'str'> | default: default
ERROR | 04/24/2023 09:24:30 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 24 | a config field_name must not be empty.
details - field_name:  | typ: <class 'str'> | default: default
ERROR | 04/24/2023 09:24:30 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 29 | typ should be a type, specifying the type of object that the config field represents.  Instead, a <class 'str'> was passed.
details - field_name: name | typ: fail | default: default
ERROR | 04/24/2023 09:25:40 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 4 | Hello
ERROR | 04/24/2023 09:25:40 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:25:40 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
ERROR | 04/24/2023 09:25:40 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:25:40 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
ERROR | 04/24/2023 09:25:40 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:25:40 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
DEBUG | 04/24/2023 09:25:40 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test
ERROR | 04/24/2023 09:25:40 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:25:40 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
ERROR | 04/24/2023 09:25:40 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:25:40 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
ERROR | 04/24/2023 09:25:40 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:25:40 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
DEBUG | 04/24/2023 09:25:40 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test
ERROR | 04/24/2023 09:25:40 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:25:40 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
ERROR | 04/24/2023 09:25:40 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:25:40 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
ERROR | 04/24/2023 09:25:40 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:25:40 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
DEBUG | 04/24/2023 09:25:40 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test
DEBUG | 04/24/2023 09:25:40 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test1
DEBUG | 04/24/2023 09:25:40 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test2
ERROR | 04/24/2023 09:25:40 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:25:40 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
DEBUG | 04/24/2023 09:25:40 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test1
ERROR | 04/24/2023 09:25:40 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:25:40 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
DEBUG | 04/24/2023 09:25:40 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test2
ERROR | 04/24/2023 09:25:40 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:25:40 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
DEBUG | 04/24/2023 09:25:40 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test1
DEBUG | 04/24/2023 09:25:40 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test2
DEBUG | 04/24/2023 09:25:40 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test1
DEBUG | 04/24/2023 09:25:40 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test2
DEBUG | 04/24/2023 09:25:40 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test3
ERROR | 04/24/2023 09:25:41 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 19 | a config field_name must be of type string.  Instead, a <class 'type'> was passed.
details - field_name: <class 'str'> | typ: <class 'str'> | default: default
ERROR | 04/24/2023 09:25:41 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 24 | a config field_name must not be empty.
details - field_name:  | typ: <class 'str'> | default: default
ERROR | 04/24/2023 09:25:41 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 29 | typ should be a type, specifying the type of object that the config field represents.  Instead, a <class 'str'> was passed.
details - field_name: name | typ: fail | default: default
ERROR | 04/24/2023 09:25:41 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 34 | default should be of the type specified by typ.  Instead, a <class 'int'> was passed.
details - field_name: name | typ: <class 'str'> | default: 0
ERROR | 04/24/2023 09:26:10 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 4 | Hello
ERROR | 04/24/2023 09:26:10 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:26:10 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
ERROR | 04/24/2023 09:26:10 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:26:10 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
ERROR | 04/24/2023 09:26:10 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:26:10 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
DEBUG | 04/24/2023 09:26:10 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test
ERROR | 04/24/2023 09:26:10 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:26:10 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
ERROR | 04/24/2023 09:26:10 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:26:10 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
ERROR | 04/24/2023 09:26:10 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:26:10 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
DEBUG | 04/24/2023 09:26:10 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test
ERROR | 04/24/2023 09:26:10 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:26:10 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
ERROR | 04/24/2023 09:26:10 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:26:10 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
ERROR | 04/24/2023 09:26:10 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:26:10 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
DEBUG | 04/24/2023 09:26:10 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test
DEBUG | 04/24/2023 09:26:10 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test1
DEBUG | 04/24/2023 09:26:10 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test2
ERROR | 04/24/2023 09:26:10 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:26:10 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
DEBUG | 04/24/2023 09:26:10 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test1
ERROR | 04/24/2023 09:26:10 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:26:10 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
DEBUG | 04/24/2023 09:26:10 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test2
ERROR | 04/24/2023 09:26:10 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:26:10 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
DEBUG | 04/24/2023 09:26:10 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test1
DEBUG | 04/24/2023 09:26:10 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test2
DEBUG | 04/24/2023 09:26:10 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test1
DEBUG | 04/24/2023 09:26:10 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test2
DEBUG | 04/24/2023 09:26:10 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test3
ERROR | 04/24/2023 09:26:10 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 19 | a config field_name must be of type string.  Instead, a <class 'type'> was passed.
details - field_name: <class 'str'> | typ: <class 'str'> | default: default
ERROR | 04/24/2023 09:26:10 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 24 | a config field_name must not be empty.
details - field_name:  | typ: <class 'str'> | default: default
ERROR | 04/24/2023 09:26:10 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 29 | typ should be a type, specifying the type of object that the config field represents.  Instead, a <class 'str'> was passed.
details - field_name: name | typ: fail | default: default
ERROR | 04/24/2023 09:26:10 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 34 | default should be of the type specified by typ.  Instead, a <class 'int'> was passed.
details - field_name: name | typ: <class 'str'> | default: 0
ERROR | 04/24/2023 09:28:05 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 4 | Hello
ERROR | 04/24/2023 09:28:05 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:28:05 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
ERROR | 04/24/2023 09:28:05 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:28:05 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
ERROR | 04/24/2023 09:28:05 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:28:05 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
DEBUG | 04/24/2023 09:28:05 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test
ERROR | 04/24/2023 09:28:05 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:28:05 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
ERROR | 04/24/2023 09:28:05 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:28:05 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
ERROR | 04/24/2023 09:28:05 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:28:05 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
DEBUG | 04/24/2023 09:28:05 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test
ERROR | 04/24/2023 09:28:05 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:28:05 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
ERROR | 04/24/2023 09:28:05 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:28:05 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
ERROR | 04/24/2023 09:28:05 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:28:05 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
DEBUG | 04/24/2023 09:28:05 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test
DEBUG | 04/24/2023 09:28:05 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test1
DEBUG | 04/24/2023 09:28:05 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test2
ERROR | 04/24/2023 09:28:05 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:28:05 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
DEBUG | 04/24/2023 09:28:05 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test1
ERROR | 04/24/2023 09:28:05 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:28:05 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
DEBUG | 04/24/2023 09:28:05 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test2
ERROR | 04/24/2023 09:28:05 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:28:05 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
DEBUG | 04/24/2023 09:28:05 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test1
DEBUG | 04/24/2023 09:28:05 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test2
DEBUG | 04/24/2023 09:28:05 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test1
DEBUG | 04/24/2023 09:28:05 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test2
DEBUG | 04/24/2023 09:28:05 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test3
ERROR | 04/24/2023 09:28:05 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 19 | a config field_name must be of type string.  Instead, a <class 'type'> was passed.
details - field_name: <class 'str'> | typ: <class 'str'> | default: default
ERROR | 04/24/2023 09:28:05 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 24 | a config field_name must not be empty.
details - field_name:  | typ: <class 'str'> | default: default
ERROR | 04/24/2023 09:28:05 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 29 | typ should be a type, specifying the type of object that the config field represents.  Instead, a <class 'str'> was passed.
details - field_name: name | typ: fail | default: default
ERROR | 04/24/2023 09:28:05 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 34 | default should be of the type specified by typ.  Instead, a <class 'int'> was passed.
details - field_name: name | typ: <class 'str'> | default: 0
ERROR | 04/24/2023 09:29:08 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 4 | Hello
ERROR | 04/24/2023 09:29:08 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:29:08 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
ERROR | 04/24/2023 09:29:08 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:29:08 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
ERROR | 04/24/2023 09:29:08 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:29:08 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
DEBUG | 04/24/2023 09:29:08 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test
ERROR | 04/24/2023 09:29:08 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:29:08 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
ERROR | 04/24/2023 09:29:08 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:29:08 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
ERROR | 04/24/2023 09:29:08 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:29:08 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
DEBUG | 04/24/2023 09:29:08 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test
ERROR | 04/24/2023 09:29:08 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:29:08 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
ERROR | 04/24/2023 09:29:08 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:29:08 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
ERROR | 04/24/2023 09:29:08 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:29:08 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
DEBUG | 04/24/2023 09:29:08 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test
DEBUG | 04/24/2023 09:29:08 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test1
DEBUG | 04/24/2023 09:29:08 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test2
ERROR | 04/24/2023 09:29:08 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:29:08 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
DEBUG | 04/24/2023 09:29:08 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test1
ERROR | 04/24/2023 09:29:08 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:29:08 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
DEBUG | 04/24/2023 09:29:08 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test2
ERROR | 04/24/2023 09:29:08 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:29:08 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
DEBUG | 04/24/2023 09:29:08 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test1
DEBUG | 04/24/2023 09:29:08 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test2
DEBUG | 04/24/2023 09:29:08 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test1
DEBUG | 04/24/2023 09:29:08 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test2
DEBUG | 04/24/2023 09:29:08 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test3
ERROR | 04/24/2023 09:29:08 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 19 | a config field_name must be of type string.  Instead, a <class 'type'> was passed.
details - field_name: <class 'str'> | typ: <class 'str'> | default: default
ERROR | 04/24/2023 09:29:08 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 24 | a config field_name must not be empty.
details - field_name:  | typ: <class 'str'> | default: default
ERROR | 04/24/2023 09:29:08 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 29 | typ should be a type, specifying the type of object that the config field represents.  Instead, a <class 'str'> was passed.
details - field_name: name | typ: fail | default: default
ERROR | 04/24/2023 09:29:08 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 34 | default should be of the type specified by typ.  Instead, a <class 'int'> was passed.
details - field_name: name | typ: <class 'str'> | default: 0
ERROR | 04/24/2023 09:33:19 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 4 | Hello
ERROR | 04/24/2023 09:33:19 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:33:19 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
ERROR | 04/24/2023 09:33:19 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:33:19 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
ERROR | 04/24/2023 09:33:19 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:33:19 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
DEBUG | 04/24/2023 09:33:19 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test
ERROR | 04/24/2023 09:33:19 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:33:19 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
ERROR | 04/24/2023 09:33:19 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:33:19 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
ERROR | 04/24/2023 09:33:19 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:33:19 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
DEBUG | 04/24/2023 09:33:19 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test
ERROR | 04/24/2023 09:33:19 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:33:19 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
ERROR | 04/24/2023 09:33:19 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:33:19 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
ERROR | 04/24/2023 09:33:19 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:33:19 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
DEBUG | 04/24/2023 09:33:19 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test
DEBUG | 04/24/2023 09:33:19 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test1
DEBUG | 04/24/2023 09:33:19 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test2
ERROR | 04/24/2023 09:33:19 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:33:19 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
DEBUG | 04/24/2023 09:33:19 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test1
ERROR | 04/24/2023 09:33:19 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:33:19 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
DEBUG | 04/24/2023 09:33:19 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test2
ERROR | 04/24/2023 09:33:19 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:33:19 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
DEBUG | 04/24/2023 09:33:19 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test1
DEBUG | 04/24/2023 09:33:19 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test2
DEBUG | 04/24/2023 09:33:19 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test1
DEBUG | 04/24/2023 09:33:19 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test2
DEBUG | 04/24/2023 09:33:19 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test3
ERROR | 04/24/2023 09:33:19 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 22 | a config field_name must be of type string.  Instead, a <class 'type'> was passed.
details - field_name: <class 'str'> | typ: <class 'str'> | default: default
ERROR | 04/24/2023 09:33:19 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 27 | a config field_name must not be empty.
details - field_name:  | typ: <class 'str'> | default: default
ERROR | 04/24/2023 09:33:19 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 32 | typ should be a type, specifying the type of object that the config field represents.  Instead, a <class 'str'> was passed.
details - field_name: name | typ: fail | default: default
ERROR | 04/24/2023 09:33:19 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 37 | default should be of the type specified by typ.  Instead, a <class 'int'> was passed.
details - field_name: name | typ: <class 'str'> | default: 0
ERROR | 04/24/2023 09:33:41 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 4 | Hello
ERROR | 04/24/2023 09:33:42 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:33:42 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
ERROR | 04/24/2023 09:33:42 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:33:42 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
ERROR | 04/24/2023 09:33:42 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:33:42 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
DEBUG | 04/24/2023 09:33:42 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test
ERROR | 04/24/2023 09:33:42 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:33:42 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
ERROR | 04/24/2023 09:33:42 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:33:42 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
ERROR | 04/24/2023 09:33:42 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:33:42 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
DEBUG | 04/24/2023 09:33:42 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test
ERROR | 04/24/2023 09:33:42 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:33:42 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
ERROR | 04/24/2023 09:33:42 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:33:42 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
ERROR | 04/24/2023 09:33:42 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:33:42 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
DEBUG | 04/24/2023 09:33:42 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test
DEBUG | 04/24/2023 09:33:42 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test1
DEBUG | 04/24/2023 09:33:42 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test2
ERROR | 04/24/2023 09:33:42 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:33:42 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
DEBUG | 04/24/2023 09:33:42 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test1
ERROR | 04/24/2023 09:33:42 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:33:42 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
DEBUG | 04/24/2023 09:33:42 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test2
ERROR | 04/24/2023 09:33:42 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:33:42 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
DEBUG | 04/24/2023 09:33:42 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test1
DEBUG | 04/24/2023 09:33:42 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test2
DEBUG | 04/24/2023 09:33:42 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test1
DEBUG | 04/24/2023 09:33:42 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test2
DEBUG | 04/24/2023 09:33:42 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test3
ERROR | 04/24/2023 09:33:42 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 22 | a config field_name must be of type string.  Instead, a <class 'type'> was passed.
details - field_name: <class 'str'> | typ: <class 'str'> | default: default
ERROR | 04/24/2023 09:33:42 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 27 | a config field_name must not be empty.
details - field_name:  | typ: <class 'str'> | default: default
ERROR | 04/24/2023 09:33:42 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 32 | typ should be a type, specifying the type of object that the config field represents.  Instead, a <class 'str'> was passed.
details - field_name: name | typ: fail | default: default
ERROR | 04/24/2023 09:33:42 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 37 | default should be of the type specified by typ.  Instead, a <class 'int'> was passed.
details - field_name: name | typ: <class 'str'> | default: 0
ERROR | 04/24/2023 09:33:44 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 4 | Hello
ERROR | 04/24/2023 09:33:44 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:33:44 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
ERROR | 04/24/2023 09:33:44 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:33:44 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
ERROR | 04/24/2023 09:33:44 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:33:44 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
DEBUG | 04/24/2023 09:33:44 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test
ERROR | 04/24/2023 09:33:44 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:33:44 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
ERROR | 04/24/2023 09:33:44 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:33:44 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
ERROR | 04/24/2023 09:33:44 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:33:44 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
DEBUG | 04/24/2023 09:33:44 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test
ERROR | 04/24/2023 09:33:44 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:33:44 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
ERROR | 04/24/2023 09:33:44 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:33:44 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
ERROR | 04/24/2023 09:33:44 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:33:44 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
DEBUG | 04/24/2023 09:33:44 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test
DEBUG | 04/24/2023 09:33:44 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test1
DEBUG | 04/24/2023 09:33:44 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test2
ERROR | 04/24/2023 09:33:44 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:33:44 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
DEBUG | 04/24/2023 09:33:44 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test1
ERROR | 04/24/2023 09:33:44 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:33:44 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
DEBUG | 04/24/2023 09:33:44 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test2
ERROR | 04/24/2023 09:33:44 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:33:44 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
DEBUG | 04/24/2023 09:33:44 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test1
DEBUG | 04/24/2023 09:33:44 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test2
DEBUG | 04/24/2023 09:33:44 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test1
DEBUG | 04/24/2023 09:33:44 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test2
DEBUG | 04/24/2023 09:33:44 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test3
ERROR | 04/24/2023 09:33:44 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 22 | a config field_name must be of type string.  Instead, a <class 'type'> was passed.
details - field_name: <class 'str'> | typ: <class 'str'> | default: default
ERROR | 04/24/2023 09:33:44 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 27 | a config field_name must not be empty.
details - field_name:  | typ: <class 'str'> | default: default
ERROR | 04/24/2023 09:33:44 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 32 | typ should be a type, specifying the type of object that the config field represents.  Instead, a <class 'str'> was passed.
details - field_name: name | typ: fail | default: default
ERROR | 04/24/2023 09:33:44 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 37 | default should be of the type specified by typ.  Instead, a <class 'int'> was passed.
details - field_name: name | typ: <class 'str'> | default: 0
ERROR | 04/24/2023 09:34:19 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 4 | Hello
ERROR | 04/24/2023 09:34:19 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:34:19 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
ERROR | 04/24/2023 09:34:19 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:34:19 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
ERROR | 04/24/2023 09:34:19 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:34:19 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
DEBUG | 04/24/2023 09:34:19 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test
ERROR | 04/24/2023 09:34:19 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:34:19 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
ERROR | 04/24/2023 09:34:19 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:34:19 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
ERROR | 04/24/2023 09:34:19 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:34:19 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
DEBUG | 04/24/2023 09:34:19 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test
ERROR | 04/24/2023 09:34:19 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:34:19 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
ERROR | 04/24/2023 09:34:19 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:34:19 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
ERROR | 04/24/2023 09:34:19 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:34:19 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
DEBUG | 04/24/2023 09:34:19 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test
DEBUG | 04/24/2023 09:34:19 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test1
DEBUG | 04/24/2023 09:34:19 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test2
ERROR | 04/24/2023 09:34:19 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:34:19 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
DEBUG | 04/24/2023 09:34:19 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test1
ERROR | 04/24/2023 09:34:19 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:34:19 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
DEBUG | 04/24/2023 09:34:19 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test2
ERROR | 04/24/2023 09:34:19 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:34:19 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
DEBUG | 04/24/2023 09:34:19 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test1
DEBUG | 04/24/2023 09:34:19 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test2
DEBUG | 04/24/2023 09:34:19 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test1
DEBUG | 04/24/2023 09:34:19 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test2
DEBUG | 04/24/2023 09:34:19 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test3
ERROR | 04/24/2023 09:34:19 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 22 | a config field_name must be of type string.  Instead, a <class 'type'> was passed.
details - field_name: <class 'str'> | typ: <class 'str'> | default: default
ERROR | 04/24/2023 09:34:19 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 27 | a config field_name must not be empty.
details - field_name:  | typ: <class 'str'> | default: default
ERROR | 04/24/2023 09:34:19 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 32 | typ should be a type, specifying the type of object that the config field represents.  Instead, a <class 'str'> was passed.
details - field_name: name | typ: fail | default: default
ERROR | 04/24/2023 09:34:19 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 37 | default should be of the type specified by typ.  Instead, a <class 'int'> was passed.
details - field_name: name | typ: <class 'str'> | default: 0
ERROR | 04/24/2023 09:34:49 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 4 | Hello
ERROR | 04/24/2023 09:34:49 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:34:49 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
ERROR | 04/24/2023 09:34:49 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:34:49 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
ERROR | 04/24/2023 09:34:49 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:34:49 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
DEBUG | 04/24/2023 09:34:49 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test
ERROR | 04/24/2023 09:34:49 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:34:49 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
ERROR | 04/24/2023 09:34:49 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:34:49 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
ERROR | 04/24/2023 09:34:49 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:34:49 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
DEBUG | 04/24/2023 09:34:49 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test
ERROR | 04/24/2023 09:34:49 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:34:49 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
ERROR | 04/24/2023 09:34:49 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:34:49 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
ERROR | 04/24/2023 09:34:49 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:34:49 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
DEBUG | 04/24/2023 09:34:49 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test
DEBUG | 04/24/2023 09:34:49 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test1
DEBUG | 04/24/2023 09:34:49 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test2
ERROR | 04/24/2023 09:34:49 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:34:49 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
DEBUG | 04/24/2023 09:34:49 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test1
ERROR | 04/24/2023 09:34:49 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:34:49 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
DEBUG | 04/24/2023 09:34:49 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test2
ERROR | 04/24/2023 09:34:49 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:34:49 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
DEBUG | 04/24/2023 09:34:49 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test1
DEBUG | 04/24/2023 09:34:49 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test2
DEBUG | 04/24/2023 09:34:49 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test1
DEBUG | 04/24/2023 09:34:49 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test2
DEBUG | 04/24/2023 09:34:49 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test3
ERROR | 04/24/2023 09:34:49 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 22 | a config field_name must be of type string.  Instead, a <class 'type'> was passed.
details - field_name: <class 'str'> | typ: <class 'str'> | default: default
ERROR | 04/24/2023 09:34:49 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 27 | a config field_name must not be empty.
details - field_name:  | typ: <class 'str'> | default: default
ERROR | 04/24/2023 09:34:49 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 32 | typ should be a type, specifying the type of object that the config field represents.  Instead, a <class 'str'> was passed.
details - field_name: name | typ: fail | default: default
ERROR | 04/24/2023 09:34:49 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 37 | default should be of the type specified by typ.  Instead, a <class 'int'> was passed.
details - field_name: name | typ: <class 'str'> | default: 0
ERROR | 04/24/2023 09:35:04 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 4 | Hello
ERROR | 04/24/2023 09:35:04 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:35:04 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
ERROR | 04/24/2023 09:35:04 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:35:04 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
ERROR | 04/24/2023 09:35:04 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:35:04 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
DEBUG | 04/24/2023 09:35:04 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test
ERROR | 04/24/2023 09:35:04 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:35:04 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
ERROR | 04/24/2023 09:35:04 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:35:04 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
ERROR | 04/24/2023 09:35:04 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:35:04 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
DEBUG | 04/24/2023 09:35:04 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test
ERROR | 04/24/2023 09:35:04 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:35:04 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
ERROR | 04/24/2023 09:35:04 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:35:04 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
ERROR | 04/24/2023 09:35:04 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:35:04 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
DEBUG | 04/24/2023 09:35:04 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test
DEBUG | 04/24/2023 09:35:04 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test1
DEBUG | 04/24/2023 09:35:04 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test2
ERROR | 04/24/2023 09:35:04 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:35:04 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
DEBUG | 04/24/2023 09:35:04 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test1
ERROR | 04/24/2023 09:35:04 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:35:04 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
DEBUG | 04/24/2023 09:35:04 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test2
ERROR | 04/24/2023 09:35:04 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:35:04 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
DEBUG | 04/24/2023 09:35:04 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test1
DEBUG | 04/24/2023 09:35:04 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test2
DEBUG | 04/24/2023 09:35:04 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test1
DEBUG | 04/24/2023 09:35:04 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test2
DEBUG | 04/24/2023 09:35:04 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test3
ERROR | 04/24/2023 09:35:04 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 22 | a config field_name must be of type string.  Instead, a <class 'type'> was passed.
details - field_name: <class 'str'> | typ: <class 'str'> | default: default
ERROR | 04/24/2023 09:35:04 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 27 | a config field_name must not be empty.
details - field_name:  | typ: <class 'str'> | default: default
ERROR | 04/24/2023 09:35:04 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 32 | typ should be a type, specifying the type of object that the config field represents.  Instead, a <class 'str'> was passed.
details - field_name: name | typ: fail | default: default
ERROR | 04/24/2023 09:35:04 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 37 | default should be of the type specified by typ.  Instead, a <class 'int'> was passed.
details - field_name: name | typ: <class 'str'> | default: 0
ERROR | 04/24/2023 09:38:37 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 4 | Hello
ERROR | 04/24/2023 09:38:37 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:38:37 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
ERROR | 04/24/2023 09:38:37 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:38:37 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
ERROR | 04/24/2023 09:38:37 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:38:37 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
DEBUG | 04/24/2023 09:38:37 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test
ERROR | 04/24/2023 09:38:37 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:38:37 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
ERROR | 04/24/2023 09:38:37 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:38:37 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
ERROR | 04/24/2023 09:38:37 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:38:37 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
DEBUG | 04/24/2023 09:38:37 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test
ERROR | 04/24/2023 09:38:37 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:38:37 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
ERROR | 04/24/2023 09:38:37 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:38:37 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
ERROR | 04/24/2023 09:38:37 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:38:37 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
DEBUG | 04/24/2023 09:38:37 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test
DEBUG | 04/24/2023 09:38:37 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test1
DEBUG | 04/24/2023 09:38:37 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test2
ERROR | 04/24/2023 09:38:37 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:38:37 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
DEBUG | 04/24/2023 09:38:37 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test1
ERROR | 04/24/2023 09:38:37 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:38:37 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
DEBUG | 04/24/2023 09:38:37 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test2
ERROR | 04/24/2023 09:38:37 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:38:37 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
DEBUG | 04/24/2023 09:38:37 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test1
DEBUG | 04/24/2023 09:38:37 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test2
DEBUG | 04/24/2023 09:38:37 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test1
DEBUG | 04/24/2023 09:38:37 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test2
DEBUG | 04/24/2023 09:38:37 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test3
ERROR | 04/24/2023 09:38:37 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 22 | a config field_name must be of type string.  Instead, a <class 'type'> was passed.
details - field_name: <class 'str'> | typ: <class 'str'> | default: default
ERROR | 04/24/2023 09:38:37 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 27 | a config field_name must not be empty.
details - field_name:  | typ: <class 'str'> | default: default
ERROR | 04/24/2023 09:38:37 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 32 | typ should be a type, specifying the type of object that the config field represents.  Instead, a <class 'str'> was passed.
details - field_name: name | typ: fail | default: default
ERROR | 04/24/2023 09:38:37 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 37 | default should be of the type specified by typ.  Instead, a <class 'int'> was passed.
details - field_name: name | typ: <class 'str'> | default: 0
ERROR | 04/24/2023 09:38:37 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 42 | config field test already exists inside of namespace pytest.
details - field_name: test | typ: <class 'str'> | default: testing
ERROR | 04/24/2023 09:39:00 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 4 | Hello
ERROR | 04/24/2023 09:39:00 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:39:00 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
ERROR | 04/24/2023 09:39:00 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:39:00 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
ERROR | 04/24/2023 09:39:00 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:39:00 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
DEBUG | 04/24/2023 09:39:00 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test
ERROR | 04/24/2023 09:39:00 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:39:00 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
ERROR | 04/24/2023 09:39:00 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:39:00 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
ERROR | 04/24/2023 09:39:00 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:39:00 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
DEBUG | 04/24/2023 09:39:00 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test
ERROR | 04/24/2023 09:39:00 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:39:00 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
ERROR | 04/24/2023 09:39:00 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:39:00 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
ERROR | 04/24/2023 09:39:00 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:39:00 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
DEBUG | 04/24/2023 09:39:00 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test
DEBUG | 04/24/2023 09:39:00 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test1
DEBUG | 04/24/2023 09:39:00 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test2
ERROR | 04/24/2023 09:39:00 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:39:00 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
DEBUG | 04/24/2023 09:39:00 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test1
ERROR | 04/24/2023 09:39:00 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:39:00 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
DEBUG | 04/24/2023 09:39:00 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test2
ERROR | 04/24/2023 09:39:00 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:39:00 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
DEBUG | 04/24/2023 09:39:00 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test1
DEBUG | 04/24/2023 09:39:00 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test2
DEBUG | 04/24/2023 09:39:00 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test1
DEBUG | 04/24/2023 09:39:00 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test2
DEBUG | 04/24/2023 09:39:00 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test3
ERROR | 04/24/2023 09:39:00 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 22 | a config field_name must be of type string.  Instead, a <class 'type'> was passed.
details - field_name: <class 'str'> | typ: <class 'str'> | default: default
ERROR | 04/24/2023 09:39:00 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 27 | a config field_name must not be empty.
details - field_name:  | typ: <class 'str'> | default: default
ERROR | 04/24/2023 09:39:00 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 32 | typ should be a type, specifying the type of object that the config field represents.  Instead, a <class 'str'> was passed.
details - field_name: name | typ: fail | default: default
ERROR | 04/24/2023 09:39:00 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 37 | default should be of the type specified by typ.  Instead, a <class 'int'> was passed.
details - field_name: name | typ: <class 'str'> | default: 0
ERROR | 04/24/2023 09:39:00 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 42 | config field test already exists inside of namespace pytest.
details - field_name: test | typ: <class 'str'> | default: testing
ERROR | 04/24/2023 09:39:52 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 4 | Hello
ERROR | 04/24/2023 09:39:52 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:39:52 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
ERROR | 04/24/2023 09:39:52 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:39:52 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
ERROR | 04/24/2023 09:39:52 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:39:52 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
DEBUG | 04/24/2023 09:39:52 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test
ERROR | 04/24/2023 09:39:52 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:39:52 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
ERROR | 04/24/2023 09:39:52 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:39:52 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
ERROR | 04/24/2023 09:39:52 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:39:52 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
DEBUG | 04/24/2023 09:39:52 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test
ERROR | 04/24/2023 09:39:52 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:39:52 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
ERROR | 04/24/2023 09:39:52 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:39:52 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
ERROR | 04/24/2023 09:39:52 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:39:52 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
DEBUG | 04/24/2023 09:39:52 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test
DEBUG | 04/24/2023 09:39:52 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test1
DEBUG | 04/24/2023 09:39:52 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test2
ERROR | 04/24/2023 09:39:52 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/24/2023 09:39:52 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to properties_config.ini
DEBUG | 04/24/2023 09:39:52 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test1
ERROR | 04/24/2023 09:39:52 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/24/2023 09:39:52 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to local
DEBUG | 04/24/2023 09:39:52 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test2
ERROR | 04/24/2023 09:39:52 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 86 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/24/2023 09:39:52 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to debug
DEBUG | 04/24/2023 09:39:52 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test1
DEBUG | 04/24/2023 09:39:52 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test2
DEBUG | 04/24/2023 09:39:52 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 62 | LOG_LEVEL set to test1
DEBUG | 04/24/2023 09:39:52 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 65 | APP_ENVIRONMENT set to test2
DEBUG | 04/24/2023 09:39:52 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 68 | APP_CONFIG_LOCATION set to test3
ERROR | 04/24/2023 09:39:52 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 22 | a config field_name must be of type string.  Instead, a <class 'type'> was passed.
details - field_name: <class 'str'> | typ: <class 'str'> | default: default
ERROR | 04/24/2023 09:39:52 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 27 | a config field_name must not be empty.
details - field_name:  | typ: <class 'str'> | default: default
ERROR | 04/24/2023 09:39:52 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 32 | typ should be a type, specifying the type of object that the config field represents.  Instead, a <class 'str'> was passed.
details - field_name: name | typ: fail | default: default
ERROR | 04/24/2023 09:39:52 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 37 | default should be of the type specified by typ.  Instead, a <class 'int'> was passed.
details - field_name: name | typ: <class 'str'> | default: 0
ERROR | 04/24/2023 09:39:52 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 42 | config field test already exists inside of namespace pytest.
details - field_name: test | typ: <class 'str'> | default: testing
ERROR | 04/24/2023 09:39:52 AM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 42 | config field test already exists inside of namespace pytest.
details - field_name: test | typ: <class 'int'> | default: 0
